# Step 3: Selecting Robust Policies Based on Signal to Noise & Maximised Regret

### Loading & Filtering Data

In [1]:

import pandas as pd
from ema_workbench import ema_logging, load_results
from ema_workbench.analysis.plotting import lines

C:\Users\irene\anaconda3\lib\site-packages\ema_workbench\em_framework\evaluators.py:21: UserWarning: ipyparallel not installed - IpyparalleEvaluator not available
  warnings.warn(
C:\Users\irene\anaconda3\lib\site-packages\ema_workbench\analysis\prim.py:30: ImportWarning: altair based interactive inspection not available
  warnings.warn(("altair based interactive "

In [19]:
scores_sn=pd.read_excel('./Data/scores_step3_sn.xlsx')
scores_mr=pd.read_excel('./Data/scores_step3_mr.xlsx')


scores_sn = scores_sn.rename(columns={'Unnamed: 0': 'policy_sn'})

In [20]:

q25_food = scores_sn['Average food provision by MF'].quantile(q=0.2) 
q25_vm = scores_sn['Average vertical migration'].quantile(q=0.2)
q25_bio = scores_sn['Biomass MF 10th percentile'].quantile(q=0.2)
q25_atm = scores_sn['Final atmospheric C level'].quantile(q=0.2) 


filtered_food = scores_sn[scores_sn['Average food provision by MF']>=q25_food]
filtered_vm = filtered_food[filtered_food['Average vertical migration']>=q25_vm]
filtered_bio = filtered_vm[filtered_vm['Biomass MF 10th percentile']>=q25_bio]
filtered_all_sn = filtered_bio[filtered_bio['Final atmospheric C level']>=q25_atm]


filtered_all_sn.to_excel('./Data/filtered_all_sn.xlsx')
filtered_all_sn

,policy_sn,Average food provision by MF,Average vertical migration,Biomass MF 10th percentile,Final atmospheric C level,Inertia
2,2,0.032486,10.143211,31.239853,6.925307,1.473484e+13
3,3,0.028704,9.989696,31.673929,6.929968,2.030173e+13
4,4,0.028784,9.992888,31.675802,6.929900,1.895454e+13
5,5,0.028774,9.992885,31.671150,6.929890,7.225026e+13
9,9,0.028718,9.990662,31.676070,6.929991,2.030173e+13

In [21]:

q25_food = scores_mr['Average food provision by MF'].quantile(q=0.8)
q25_vm = scores_mr['Average vertical migration'].quantile(q=0.8)
q25_bio = scores_mr['Biomass MF 10th percentile'].quantile(q=0.8)
q25_atm = scores_mr['Final atmospheric C level'].quantile(q=0.8)


filtered_food_mr = scores_mr[scores_mr['Average food provision by MF']<=q25_food]
filtered_vm_mr = filtered_food_mr[filtered_food_mr['Average vertical migration']<=q25_vm]
filtered_bio_mr = filtered_vm_mr[filtered_vm_mr['Biomass MF 10th percentile']<=q25_bio]
filtered_all_mr = filtered_bio_mr[filtered_bio_mr['Final atmospheric C level']<=q25_atm]

filtered_all_mr.to_excel('./Data/filtered_all_mr.xlsx')
filtered_food_mr

,policy,Average food provision by MF,Average vertical migration,Biomass MF 10th percentile,Final atmospheric C level,Inertia
0,0,0.115357,0.389391,3.359312,36.060425,0.045455
1,1,0.230485,1.329478,7.732240,34.876465,0.045455
2,2,0.101028,0.248108,3.880446,35.060486,0.045455
3,3,0.344659,2.065831,10.459405,16.043213,0.068182
4,4,0.344659,2.053149,9.635540,15.441650,0.090909
5,5,0.344659,2.037448,9.634362,16.005249,0.000000
6,6,0.344659,2.169938,10.446153,5.934570,0.090909
7,7,0.104844,0.276649,2.465138,34.856934,0.045455
8,8,0.344659,2.156468,10.439899,14.175781,0.113636
9,9,0.344659,2.065831,10.459434,15.739868,0.068182

In [22]:
# keep only the duplicates of these two dataframes

ids = filtered_all_sn['policy_sn'].values


filtered_all = filtered_all_mr [filtered_all_mr['policy'].isin(ids)]
filtered_all

,policy,Average food provision by MF,Average vertical migration,Biomass MF 10th percentile,Final atmospheric C level,Inertia
4,4,0.344659,2.053149,9.635540,15.441650,0.090909
5,5,0.344659,2.037448,9.634362,16.005249,0.000000

In [23]:
# get the policies for these policy numbers

file_name = './Data/results_step3_7.tar.gz' 
experiments_all, outcomes_all = load_results(file_name)

In [25]:
policies = experiments_all.drop(['scenario', 'model'], axis=1)
policies = policies.iloc[: , -46:]
policies

,Proposed harvesting quota 0,Proposed harvesting quota 1,Proposed harvesting quota 2,Proposed harvesting quota 3,Proposed harvesting quota 4,Proposed harvesting quota 5,Proposed harvesting quota 6,Proposed harvesting quota 7,Proposed harvesting quota 8,Proposed harvesting quota 9,...,Proposed harvesting quota 36,Proposed harvesting quota 37,Proposed harvesting quota 38,Proposed harvesting quota 39,Proposed harvesting quota 40,Proposed harvesting quota 41,Proposed harvesting quota 42,Proposed harvesting quota 43,Proposed harvesting quota 44,policy
0,5.488693,5.445391,5.513103,5.993686,5.984508,5.994977,5.997776,5.997402,5.962806,5.923944,...,4.539394,4.525257,4.583810,4.552944,4.567042,4.549767,4.580060,4.630359,1.286185,0
1,5.488693,5.445391,5.513103,5.993686,5.984508,5.994977,5.997776,5.997402,5.962806,5.923944,...,4.539394,4.525257,4.583810,4.552944,4.567042,4.549767,4.580060,4.630359,1.286185,0
2,5.488693,5.445391,5.513103,5.993686,5.984508,5.994977,5.997776,5.997402,5.962806,5.923944,...,4.539394,4.525257,4.583810,4.552944,4.567042,4.549767,4.580060,4.630359,1.286185,0
3,5.488693,5.445391,5.513103,5.993686,5.984508,5.994977,5.997776,5.997402,5.962806,5.923944,...,4.539394,4.525257,4.583810,4.552944,4.567042,4.549767,4.580060,4.630359,1.286185,0
4,5.488693,5.445391,5.513103,5.993686,5.984508,5.994977,5.997776,5.997402,5.962806,5.923944,...,4.539394,4.525257,4.583810,4.552944,4.567042,4.549767,4.580060,4.630359,1.286185,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,5.493312,5.444280,5.510904,5.938994,5.983407,5.992122,5.997436,5.992562,5.969942,5.999033,...,4.528078,4.523699,4.471713,4.482982,4.524310,4.517081,4.545243,4.598656,5.002779,9
29996,5.493312,5.444280,5.510904,5.938994,5.983407,5.992122,5.997436,5.992562,5.969942,5.999033,...,4.528078,4.523699,4.471713,4.482982,4.524310,4.517081,4.545243,4.598656,5.002779,9
29997,5.493312,5.444280,5.510904,5.938994,5.983407,5.992122,5.997436,5.992562,5.969942,5.999033,...,4.528078,4.523699,4.471713,4.482982,4.524310,4.517081,4.545243,4.598656,5.002779,9
29998,5.493312,5.444280,5.510904,5.938994,5.983407,5.992122,5.997436,5.992562,5.969942,5.999033,...,4.528078,4.523699,4.471713,4.482982,4.524310,4.517081,4.545243,4.598656,5.002779,9
29999,5.493312,5.444280,5.510904,5.938994,5.983407,5.992122,5.997436,5.992562,5.969942,5.999033,...,4.528078,4.523699,4.471713,4.482982,4.524310,4.517081,4.545243,4.598656,5.002779,9

In [26]:
# get the policies out of dataframe of experiments from step 3
ids_2 = filtered_all['policy'].values
filtered_all_policies = policies[policies['policy'].isin(ids_2)]
filtered_all_policies = filtered_all_policies.drop_duplicates(subset='policy', keep="first")
filtered_all_policies= filtered_all_policies.drop(['policy'], axis=1)
filtered_all_policies.to_excel('./Data/filtered_policies.xlsx')

In [27]:
filtered_all_policies

,Proposed harvesting quota 0,Proposed harvesting quota 1,Proposed harvesting quota 2,Proposed harvesting quota 3,Proposed harvesting quota 4,Proposed harvesting quota 5,Proposed harvesting quota 6,Proposed harvesting quota 7,Proposed harvesting quota 8,Proposed harvesting quota 9,...,Proposed harvesting quota 35,Proposed harvesting quota 36,Proposed harvesting quota 37,Proposed harvesting quota 38,Proposed harvesting quota 39,Proposed harvesting quota 40,Proposed harvesting quota 41,Proposed harvesting quota 42,Proposed harvesting quota 43,Proposed harvesting quota 44
12000,5.491059,5.444262,5.510904,5.938919,5.983407,5.992127,5.997443,5.929798,5.969624,5.901823,...,4.514762,4.528083,4.523651,4.471708,4.480812,4.524310,4.519397,4.545243,4.598656,4.655942
15000,5.491239,5.443735,5.510887,5.922931,5.983381,5.992445,5.939761,5.952485,5.969405,5.994358,...,4.514762,4.463967,4.520716,4.471370,4.483149,4.526866,4.518087,4.539937,4.431970,5.265770